import {
  User,
  Course,
  Classroom,
  ClassroomTeacher,
  LearningIndicator,
  CourseLearningIndicator,
  Assignment,
  Question,
  Submission,
  SubmissionAnswer,
  SubmissionEvent,
} from '@/types/database';

export const mockTeacher: User = {
  id: 'teacher-tippanan',
  first_name: 'ธิปนรรจ์',
  last_name: 'พรายหนู',
  role: 'teacher',
  email: 'tippanan.p@pudding.ac.th',
  avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
};

export const mockCoTeacher1: User = {
  id: 'teacher-somchai',
  first_name: 'สมชาย',
  last_name: 'วิทยากร',
  role: 'teacher',
  email: 'somchai.w@pudding.ac.th',
  avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
};

export const mockCoTeacher2: User = {
  id: 'teacher-pattra',
  first_name: 'ภัทรา',
  last_name: 'สิริวัฒน์',
  role: 'teacher',
  email: 'pattra.s@pudding.ac.th',
  avatar_url: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
};

export const defaultTeachersList: ClassroomTeacher[] = [
  {
    teacher_id: 'teacher-tippanan',
    name: 'ครูธิปนรรจ์ พรายหนู (Primary Owner)',
    email: 'tippanan.p@pudding.ac.th',
    avatar_url: mockTeacher.avatar_url,
    role: 'primary',
  },
  {
    teacher_id: 'teacher-somchai',
    name: 'ครูสมชาย วิทยากร (Co-Teacher / IRR Evaluator)',
    email: 'somchai.w@pudding.ac.th',
    avatar_url: mockCoTeacher1.avatar_url,
    role: 'assistant',
  },
  {
    teacher_id: 'teacher-pattra',
    name: 'ครูภัทรา สิริวัฒน์ (Assistant Grader)',
    email: 'pattra.s@pudding.ac.th',
    avatar_url: mockCoTeacher2.avatar_url,
    role: 'assistant',
  },
];

export const mockStudents: User[] = [
  {
    id: 'std-001',
    student_id: '54101',
    first_name: 'กัญญาณัฐ',
    last_name: 'พงษ์ไพศาล',
    role: 'student',
    email: 'kanyanat.p@student.school.ac.th',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'std-002',
    student_id: '54102',
    first_name: 'ภัทรพล',
    last_name: 'เจริญวิทย์',
    role: 'student',
    email: 'pattarapol.c@student.school.ac.th',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'std-003',
    student_id: '54103',
    first_name: 'ธนกฤต',
    last_name: 'ชัยมงคล',
    role: 'student',
    email: 'thanakrit.c@student.school.ac.th',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'std-004',
    student_id: '54104',
    first_name: 'ชนัญชิดา',
    last_name: 'สุขเกษม',
    role: 'student',
    email: 'chananchida.s@student.school.ac.th',
    avatar_url: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'std-005',
    student_id: '54105',
    first_name: 'วรภัทร',
    last_name: 'เกียรติบำรุง',
    role: 'student',
    email: 'woraphat.k@student.school.ac.th',
    avatar_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'std-006',
    student_id: '54106',
    first_name: 'พิมพ์ชนก',
    last_name: 'รัตนสิริ',
    role: 'student',
    email: 'pimchanok.r@student.school.ac.th',
    avatar_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
  },
];

export const mockCourses: Course[] = [
  {
    id: 'course-thai-comm',
    code: 'ท31101',
    name: 'ภาษาไทยเพื่อการสื่อสารร่วมสมัย (Thai Communication)',
    description: 'หลักสูตรแกนกลาง สพฐ. การอ่านวิเคราะห์สาร การพูดในที่สาธารณะ การใช้ระดับภาษา และการวิพากษ์สื่อยุคใหม่',
    academic_year: 'ภาคเรียนที่ 1 / 2569',
    semester: 1,
    year_ce: 2026,
    primary_teacher_id: 'teacher-tippanan',
    teachers: defaultTeachersList,
    classroom_ids: ['class-401', 'class-402'],
    indicators: [
      {
        id: 'ind-001',
        course_id: 'course-thai-comm',
        code: 'ท 1.1 ม.4/1',
        title: 'อ่านออกเสียงและอ่านจับใจความสำคัญ วิเคราะห์ข้อเท็จจริงและข้อคิดเห็น',
        weight: 35,
        order_index: 1,
      },
      {
        id: 'ind-002',
        course_id: 'course-thai-comm',
        code: 'ท 3.1 ม.4/2',
        title: 'วิเคราะห์ วิจารณ์เรื่องที่ฟังและดูอย่างมีเหตุผลเพื่อนำข้อคิดไปประยุกต์ใช้',
        weight: 35,
        order_index: 2,
      },
      {
        id: 'ind-003',
        course_id: 'course-thai-comm',
        code: 'ท 4.1 ม.4/1',
        title: 'อธิบายธรรมชาติของภาษา พลังของภาษา และลักษณะของภาษาไทยในยุคดิจิทัล',
        weight: 30,
        order_index: 3,
      },
    ],
    created_at: '2026-05-10T08:00:00Z',
  },
  {
    id: 'course-thai-reading',
    code: 'ท31102',
    name: 'การอ่านและการเขียนเชิงสร้างสรรค์ (Thai Reading & Writing)',
    description: 'ทักษะการอ่านเชิงวิพากษ์ การเรียบเรียงความเรียงเชิงสร้างสรรค์ และการใช้โวหารภาพพจน์',
    academic_year: 'ภาคเรียนที่ 1 / 2569',
    semester: 1,
    year_ce: 2026,
    primary_teacher_id: 'teacher-tippanan',
    teachers: [
      defaultTeachersList[0],
      defaultTeachersList[1],
    ],
    classroom_ids: ['class-403'],
    indicators: [
      {
        id: 'ind-004',
        course_id: 'course-thai-reading',
        code: 'ท 2.1 ม.4/1',
        title: 'เขียนสื่อสารในรูปแบบต่างๆ เช่น บรรยาย พรรณนา เรียงความ โน้มน้าวใจ',
        weight: 50,
        order_index: 1,
      },
      {
        id: 'ind-005',
        course_id: 'course-thai-reading',
        code: 'ท 2.1 ม.4/3',
        title: 'เขียนรายงานการศึกษาค้นคว้าเชิงวิชาการตามหลักการอ้างอิงข้อมูล',
        weight: 50,
        order_index: 2,
      },
    ],
    created_at: '2026-05-12T08:00:00Z',
  },
  {
    id: 'course-thai-lit',
    code: 'ท32101',
    name: 'วรรณคดีวิจักษ์และการใช้ภาษาไทย (Thai Literature & Language Principles)',
    description: 'การวิเคราะห์คุณค่าทางวรรณศิลป์ สภาพสังคมและวัฒนธรรมไทยจากวรรณคดีชิ้นเอก',
    academic_year: 'ภาคเรียนที่ 1 / 2569',
    semester: 1,
    year_ce: 2026,
    primary_teacher_id: 'teacher-tippanan',
    teachers: [
      defaultTeachersList[0],
      defaultTeachersList[2],
    ],
    classroom_ids: ['class-501'],
    indicators: [
      {
        id: 'ind-006',
        course_id: 'course-thai-lit',
        code: 'ท 5.1 ม.5/1',
        title: 'วิเคราะห์และวิจารณ์วรรณคดีและวรรณกรรมตามหลักการวิจารณ์เบื้องต้น',
        weight: 50,
        order_index: 1,
      },
      {
        id: 'ind-007',
        course_id: 'course-thai-lit',
        code: 'ท 4.1 ม.5/2',
        title: 'ใช้คำและกลุ่มคำสร้างประโยคตรงตามวัตถุประสงค์และระดับภาษา',
        weight: 50,
        order_index: 2,
      },
    ],
    created_at: '2026-05-14T08:00:00Z',
  },
];

export const mockClassrooms: Classroom[] = [
  {
    id: 'class-401',
    course_id: 'course-thai-comm',
    course_name: 'ภาษาไทยเพื่อการสื่อสารร่วมสมัย (Thai Communication)',
    teacher_id: 'teacher-tippanan',
    teachers: defaultTeachersList,
    name: 'มัธยมศึกษาปีที่ 4/1 (แผนภาษา-การสื่อสาร)',
    academic_year: 'ภาคเรียนที่ 1 / 2569',
    semester: 1,
    year_ce: 2026,
    student_count: 6,
    subject_code: 'ท31101 ภาษาไทยเพื่อการสื่อสารร่วมสมัย',
    invite_code: 'THAI-401',
    students: mockStudents,
    created_at: '2026-05-15T08:00:00Z',
  },
  {
    id: 'class-402',
    course_id: 'course-thai-comm',
    course_name: 'ภาษาไทยเพื่อการสื่อสารร่วมสมัย (Thai Communication)',
    teacher_id: 'teacher-tippanan',
    teachers: defaultTeachersList,
    name: 'มัธยมศึกษาปีที่ 4/2 (แผนศิลป์-คำนวณ)',
    academic_year: 'ภาคเรียนที่ 1 / 2569',
    semester: 1,
    year_ce: 2026,
    student_count: 4,
    subject_code: 'ท31101 ภาษาไทยเพื่อการสื่อสารร่วมสมัย',
    invite_code: 'THAI-402',
    students: mockStudents.slice(0, 4),
    created_at: '2026-05-15T09:00:00Z',
  },
  {
    id: 'class-403',
    course_id: 'course-thai-reading',
    course_name: 'การอ่านและการเขียนเชิงสร้างสรรค์ (Thai Reading & Writing)',
    teacher_id: 'teacher-tippanan',
    teachers: [defaultTeachersList[0], defaultTeachersList[1]],
    name: 'มัธยมศึกษาปีที่ 4/3 (แผนวิทย์-เทคโนโลยี)',
    academic_year: 'ภาคเรียนที่ 1 / 2569',
    semester: 1,
    year_ce: 2026,
    student_count: 4,
    subject_code: 'ท31102 การอ่านและการเขียนเชิงสร้างสรรค์',
    invite_code: 'THAI-403',
    students: mockStudents.slice(2, 6),
    created_at: '2026-05-16T10:00:00Z',
  },
  {
    id: 'class-501',
    course_id: 'course-thai-lit',
    course_name: 'วรรณคดีวิจักษ์และการใช้ภาษาไทย (Thai Literature & Language Principles)',
    teacher_id: 'teacher-tippanan',
    teachers: [defaultTeachersList[0], defaultTeachersList[2]],
    name: 'มัธยมศึกษาปีที่ 5/1 (แผนสหศิลป์)',
    academic_year: 'ภาคเรียนที่ 1 / 2569',
    semester: 1,
    year_ce: 2026,
    student_count: 3,
    subject_code: 'ท32101 วรรณคดีวิจักษ์และการใช้ภาษาไทย',
    invite_code: 'THAI-501',
    students: mockStudents.slice(0, 3),
    created_at: '2026-05-16T11:00:00Z',
  },
];

export const mockLearningIndicators: LearningIndicator[] = [
  {
    id: 'ind-001',
    teacher_id: 'teacher-tippanan',
    code: 'ท 1.1 ม.4/1',
    title: 'อ่านออกเสียงและอ่านจับใจความสำคัญ วิเคราะห์ข้อเท็จจริงและข้อคิดเห็น',
    subject: 'ภาษาไทยเพื่อการสื่อสารร่วมสมัย',
    weight: 35,
    order_index: 1,
  },
  {
    id: 'ind-002',
    teacher_id: 'teacher-tippanan',
    code: 'ท 3.1 ม.4/2',
    title: 'วิเคราะห์ วิจารณ์เรื่องที่ฟังและดูอย่างมีเหตุผลเพื่อนำข้อคิดไปประยุกต์ใช้',
    subject: 'ภาษาไทยเพื่อการสื่อสารร่วมสมัย',
    weight: 35,
    order_index: 2,
  },
  {
    id: 'ind-003',
    teacher_id: 'teacher-tippanan',
    code: 'ท 4.1 ม.4/1',
    title: 'อธิบายธรรมชาติของภาษา พลังของภาษา และลักษณะของภาษาไทยในยุคดิจิทัล',
    subject: 'ภาษาไทยเพื่อการสื่อสารร่วมสมัย',
    weight: 30,
    order_index: 3,
  },
  {
    id: 'ind-004',
    teacher_id: 'teacher-tippanan',
    code: 'ท 2.1 ม.4/1',
    title: 'เขียนสื่อสารในรูปแบบต่างๆ เช่น บรรยาย พรรณนา เรียงความ โน้มน้าวใจ',
    subject: 'การอ่านและการเขียนเชิงสร้างสรรค์',
    weight: 50,
    order_index: 1,
  },
];

export const mockAssignments: Assignment[] = [
  {
    id: 'assign-001',
    course_id: 'course-thai-comm',
    classroom_id: 'class-401',
    classroom_name: 'มัธยมศึกษาปีที่ 4/1 (แผนภาษา-การสื่อสาร)',
    title: 'แบบทดสอบออนไลน์กลางภาค: การวิเคราะห์ข้อเท็จจริง ข้อคิดเห็น และระดับภาษา',
    description: 'แบบทดสอบออนไลน์พร้อมระบบป้องกันและเฝ้าระวังพฤติกรรมหน้าจอ กรุณาทำข้อสอบด้วยความซื่อสัตย์',
    is_exam: true,
    due_date: '2026-10-15T23:59:00',
    reminder_cron: '0 18 * * *',
    total_points: 20,
    status_override: 'auto',
    created_at: '2026-10-01T08:00:00',
  },
  {
    id: 'assign-002',
    course_id: 'course-thai-comm',
    classroom_id: 'class-401',
    classroom_name: 'มัธยมศึกษาปีที่ 4/1 (แผนภาษา-การสื่อสาร)',
    title: 'ใบงานเขียนความเรียง: การใช้ภาษาโน้มน้าวใจในสื่อสังคมออนไลน์',
    description: 'ให้นักเรียนเขียนความเรียง 1 หน้ากระดาษ พร้อมระบุกลวิธีทางภาษาที่ใช้ในการโน้มน้าวใจ',
    is_exam: false,
    due_date: '2026-10-08T18:00:00',
    reminder_cron: '0 16 * * *',
    total_points: 15,
    status_override: 'auto',
    sample_work_url: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=1000&auto=format&fit=crop&q=80',
    sample_work_title: 'ตัวอย่างการเขียนโครงเรื่องความเรียงเชิงวิเคราะห์และโน้มน้าวใจ',
    sample_work_description: 'ตัวอย่างการจัดย่อหน้า คำนำ เนื้อเรื่อง สรุป และการใช้คำเชื่อมประโยคที่สละสลวย',
    created_at: '2026-09-28T10:00:00',
  },
  {
    id: 'assign-003',
    course_id: 'course-thai-comm',
    classroom_id: 'class-402',
    classroom_name: 'มัธยมศึกษาปีที่ 4/2 (แผนศิลป์-คำนวณ)',
    title: 'แบบฝึกหัดวิเคราะห์สารและถอดความบทความวิชาการ',
    description: 'อ่านบทความวิชาการที่กำหนดให้ และสรุปใจความสำคัญเป็นภาษาของตนเอง',
    is_exam: false,
    due_date: '2026-10-12T20:00:00',
    reminder_cron: '0 12 * * *',
    total_points: 10,
    status_override: 'auto',
    sample_work_title: 'แนวทางการสรุปความและการตัดส่วนขยายความ',
    sample_work_description: 'เทคนิคการหาประโยคใจความสำคัญ (Topic Sentence) ในแต่ละย่อหน้า',
    created_at: '2026-09-30T14:00:00',
  },
  {
    id: 'assign-004',
    course_id: 'course-thai-lit',
    classroom_id: 'class-501',
    classroom_name: 'มัธยมศึกษาปีที่ 5/1 (แผนสหศิลป์)',
    title: 'การอ่านตีความและวิเคราะห์คุณค่าวรรณศิลป์ในบทละครพูดเรื่องมัทนะพาธา',
    description: 'วิเคราะห์การใช้ฉันทลักษณ์และคุณค่าทางวรรณศิลป์ที่สะท้อนทัศนะต่อความรัก',
    is_exam: false,
    due_date: '2026-10-20T23:59:00',
    reminder_cron: '0 18 * * *',
    total_points: 15,
    status_override: 'auto',
    created_at: '2026-10-02T09:00:00',
  },
];

export const mockQuestions: Question[] = [
  {
    id: 'q-001',
    assignment_id: 'assign-001',
    indicator_id: 'ind-001',
    type: 'short_answer',
    question_text: 'จงอธิบายความหมายและความแตกต่างระหว่าง "ข้อเท็จจริง" (Fact) และ "ข้อคิดเห็น" (Opinion) พร้อมยกตัวอย่างข้อความทั้ง 2 รูปแบบอย่างละ 1 ประโยค',
    ideal_answer: 'ข้อเท็จจริง คือ ข้อความที่สามารถพิสูจน์ยืนยันได้ มีหลักฐานหรือข้อมูลเชิงประจักษ์รองรับ เช่น "ประเทศไทยมี 76 จังหวัดและ 1 เขตบริหารพิเศษ" ส่วนข้อคิดเห็น คือ ข้อความที่แสดงความรู้สึก การคาดเดา การประเมินค่า หรือทัศนคติส่วนบุคคล เช่น "อาหารไทยเป็นอาหารที่มีรสชาติกลมกล่อมและอร่อยที่สุดในโลก"',
    rubric_criteria: 'ระบุนิยามของข้อเท็จจริงและข้อคิดเห็นได้ถูกต้อง 3 คะแนน, ยกตัวอย่างประโยคได้สอดคล้องชัดเจน 2 คะแนน รวม 5 คะแนน',
    max_score: 5,
  },
  {
    id: 'q-002',
    assignment_id: 'assign-001',
    indicator_id: 'ind-003',
    type: 'file_upload',
    question_text: 'จงสรุป "ระดับภาษา 3 ระดับ (ระดับทางการ, กึ่งทางการ, ไม่เป็นทางการ)" ในรูปแบบแผนภาพความคิด (Mind Map) ลงในสมุด พร้อมยกตัวอย่างบริบทการใช้งาน แล้วถ่ายภาพหรือสแกนเป็นไฟล์ PDF/รูปภาพอัปโหลดส่งในระบบ',
    ideal_answer: 'แผนภาพความคิดจำแนกภาษา 3 ระดับชัดเจน ระบุลักษณะภาษาและกลุ่มผู้ใช้หรือบริบท เช่น หนังสือราชการ (ทางการ), การเสวนาในชั้นเรียน (กึ่งทางการ), การคุยกับเพื่อนสนิท (ไม่เป็นทางการ)',
    rubric_criteria: 'จัดหมวดหมู่และอธิบายลักษณะภาษาครบ 3 ระดับ 3 คะแนน, ยกตัวอย่างบริบทและตกแต่งแผนภาพเป็นระเบียบ 2 คะแนน รวม 5 คะแนน',
    max_score: 5,
  },
  {
    id: 'q-003',
    assignment_id: 'assign-001',
    indicator_id: 'ind-001',
    type: 'multiple_choice',
    question_text: 'ข้อความใดต่อไปนี้เป็น "ข้อคิดเห็น" ทั้งหมด?',
    options: [
      'ก. ดวงอาทิตย์ขึ้นทางทิศตะวันออกและตกทางทิศตะวันตกตามธรรมชาติ',
      'ข. บ่ายวันนี้อากาศอบอ้าวมาก คาดว่าตอนเย็นฝนน่าจะตกหนักแน่นอน',
      'ค. พระบาทสมเด็จพระพุทธยอดฟ้าจุฬาโลกมหาราชทรงสถาปนากรุงรัตนโกสินทร์',
      'ง. น้ำบริสุทธิ์มีจุดเดือดที่ 100 องศาเซลเซียส ณ ความดันบรรยากาศ 1 บรรยากาศ',
    ],
    ideal_answer: 'ข. บ่ายวันนี้อากาศอบอ้าวมาก คาดว่าตอนเย็นฝนน่าจะตกหนักแน่นอน',
    rubric_criteria: 'เลือกตัวเลือกที่ถูกต้องได้ 5 คะแนน',
    max_score: 5,
  },
  {
    id: 'q-004',
    assignment_id: 'assign-001',
    indicator_id: 'ind-003',
    type: 'true_false',
    question_text: 'การใช้ภาษาในการเขียนหนังสือติดต่อราชการ หรือการแถลงข่าวอย่างเป็นทางการของหน่วยงานรัฐ จัดเป็นภาษา "ระดับทางการ" หรือ "พิธีการ"',
    ideal_answer: 'จริง (True)',
    rubric_criteria: 'ตอบถูกต้องได้ 5 คะแนน',
    max_score: 5,
  },
  {
    id: 'q-005',
    assignment_id: 'assign-002',
    indicator_id: 'ind-002',
    type: 'short_answer',
    question_text: 'ให้นักเรียนเขียนความเรียง 1 หน้ากระดาษ เรื่อง "การใช้ภาษาโน้มน้าวใจในสื่อสังคมออนไลน์" โดยอธิบายกลวิธีทางภาษา 3 ประการที่พบบ่อย พร้อมยกตัวอย่างข้อความประกอบ',
    ideal_answer: 'ความเรียงประกอบด้วยคำนำ เนื้อเรื่อง และสรุป ชี้ให้เห็นกลวิธีทางภาษา เช่น การใช้อารมณ์ความรู้สึก การอ้างอิงบุคคลที่มีชื่อเสียง และการใช้คำศัพท์ที่กระตุ้นความอยากได้หรือความกลัวตกรุ่น (FOMO)',
    rubric_criteria: 'โครงสร้างความเรียงถูกต้อง 5 คะแนน, การวิเคราะห์กลวิธีทางภาษาครบ 3 ประการ 5 คะแนน, ภาษาที่ใช้ถูกต้องและสละสลวย 5 คะแนน รวม 15 คะแนน',
    max_score: 15,
  },
  {
    id: 'q-006',
    assignment_id: 'assign-003',
    indicator_id: 'ind-001',
    type: 'short_answer',
    question_text: 'จงวิเคราะห์โครงสร้างบทความวิชาการที่กำหนดให้ และสรุปประเด็นหลักพร้อมข้อโต้แย้ง 1 ประเด็นเป็นสำนวนภาษาของตนเอง',
    ideal_answer: 'สรุปประเด็นหลักได้ชัดเจนว่าผู้เขียนต้องการนำเสนอผลกระทบของ AI ต่อการเรียนรู้ภาษา พร้อมชี้ข้อโต้แย้งในเรื่องความคิดสร้างสรรค์ของมนุษย์',
    rubric_criteria: 'ระบุประเด็นหลักได้ถูกต้อง 5 คะแนน, วิเคราะห์ข้อโต้แย้งได้สมเหตุสมผล 5 คะแนน รวม 10 คะแนน',
    max_score: 10,
  },
  {
    id: 'q-007',
    assignment_id: 'assign-004',
    indicator_id: 'ind-006',
    type: 'short_answer',
    question_text: 'จงวิเคราะห์คุณค่าทางวรรณศิลป์และการใช้ภาพพจน์จากบทละครพูดเรื่องมัทนะพาธาตอนที่ประทับใจ พร้อมอธิบายทัศนะต่อความรักที่กวีสะท้อนออกมา',
    ideal_answer: 'วิเคราะห์การใช้สัมผัสสระ สัมผัสอักษร และการใช้อุปมาโวหารเปรียบกุหลาบกับความรัก สะท้อนว่าความรักเป็นทั้งความสุขและความทุกข์ทรมาน',
    rubric_criteria: 'วิเคราะห์วรรณศิลป์ได้ลึกซึ้ง 8 คะแนน, ตีความทัศนะต่อความรักได้ตรงประเด็น 7 คะแนน รวม 15 คะแนน',
    max_score: 15,
  },
];

export const mockSubmissions: Submission[] = [
  {
    id: 'sub-001',
    assignment_id: 'assign-001',
    student_id: 'std-002', // ภัทรพล (Suspicious!)
    student: mockStudents[1],
    status: 'submitted',
    started_at: '2026-10-01T09:10:00',
    submitted_at: '2026-10-01T09:42:00',
    time_spent_seconds: 1920,
    tab_switch_count: 6,
    total_time_away_seconds: 145,
    is_flagged_suspicious: true,
    total_score: 19.5,
    max_total_score: 20,
  },
  {
    id: 'sub-002',
    assignment_id: 'assign-001',
    student_id: 'std-001', // กัญญาณัฐ (Clean)
    student: mockStudents[0],
    status: 'submitted',
    started_at: '2026-10-01T09:05:00',
    submitted_at: '2026-10-01T09:35:00',
    time_spent_seconds: 1800,
    tab_switch_count: 0,
    total_time_away_seconds: 0,
    is_flagged_suspicious: false,
    total_score: 19,
    max_total_score: 20,
  },
  {
    id: 'sub-003',
    assignment_id: 'assign-001',
    student_id: 'std-003', // ธนกฤต (Late & Flagged)
    student: mockStudents[2],
    status: 'late',
    started_at: '2026-10-01T10:00:00',
    submitted_at: '2026-10-01T10:55:00',
    time_spent_seconds: 3300,
    tab_switch_count: 4,
    total_time_away_seconds: 78,
    is_flagged_suspicious: true,
    total_score: undefined, // Pending evaluation
    max_total_score: 20,
  },
  {
    id: 'sub-004',
    assignment_id: 'assign-001',
    student_id: 'std-004', // ชนัญชิดา (Pending grading)
    student: mockStudents[3],
    status: 'submitted',
    started_at: '2026-10-01T09:12:00',
    submitted_at: '2026-10-01T09:40:00',
    time_spent_seconds: 1680,
    tab_switch_count: 1,
    total_time_away_seconds: 12,
    is_flagged_suspicious: false,
    total_score: undefined, // Pending evaluation
    max_total_score: 20,
  },
  {
    id: 'sub-005',
    assignment_id: 'assign-001',
    student_id: 'std-005', // วรภัทร (Pending submission)
    student: mockStudents[4],
    status: 'pending',
    started_at: '2026-10-01T11:00:00',
    time_spent_seconds: 400,
    tab_switch_count: 0,
    total_time_away_seconds: 0,
    is_flagged_suspicious: false,
    total_score: undefined,
    max_total_score: 20,
  },
  {
    id: 'sub-006',
    assignment_id: 'assign-001',
    student_id: 'std-006', // พิมพ์ชนก (Clean submitted)
    student: mockStudents[5],
    status: 'submitted',
    started_at: '2026-10-01T09:08:00',
    submitted_at: '2026-10-01T09:39:00',
    time_spent_seconds: 1860,
    tab_switch_count: 1,
    total_time_away_seconds: 8,
    is_flagged_suspicious: false,
    total_score: 18,
    max_total_score: 20,
  },
  // Submissions for assign-002 (Class 401: ใบงานเขียนความเรียง)
  {
    id: 'sub-007',
    assignment_id: 'assign-002',
    student_id: 'std-001',
    student: mockStudents[0],
    status: 'submitted',
    started_at: '2026-10-03T10:00:00',
    submitted_at: '2026-10-03T11:20:00',
    time_spent_seconds: 4800,
    tab_switch_count: 1,
    total_time_away_seconds: 15,
    is_flagged_suspicious: false,
    total_score: 14.5,
    max_total_score: 15,
  },
  {
    id: 'sub-008',
    assignment_id: 'assign-002',
    student_id: 'std-002',
    student: mockStudents[1],
    status: 'submitted',
    started_at: '2026-10-03T10:15:00',
    submitted_at: '2026-10-03T11:45:00',
    time_spent_seconds: 5400,
    tab_switch_count: 2,
    total_time_away_seconds: 30,
    is_flagged_suspicious: false,
    total_score: 13,
    max_total_score: 15,
  },
  {
    id: 'sub-009',
    assignment_id: 'assign-002',
    student_id: 'std-003',
    student: mockStudents[2],
    status: 'pending', // ยังไม่ส่ง
    started_at: '2026-10-03T14:00:00',
    time_spent_seconds: 300,
    tab_switch_count: 0,
    total_time_away_seconds: 0,
    is_flagged_suspicious: false,
    total_score: undefined,
    max_total_score: 15,
  },
  {
    id: 'sub-010',
    assignment_id: 'assign-002',
    student_id: 'std-004',
    student: mockStudents[3],
    status: 'submitted',
    started_at: '2026-10-03T10:30:00',
    submitted_at: '2026-10-03T11:50:00',
    time_spent_seconds: 4800,
    tab_switch_count: 0,
    total_time_away_seconds: 0,
    is_flagged_suspicious: false,
    total_score: undefined, // รอตรวจ
    max_total_score: 15,
  },
  {
    id: 'sub-011',
    assignment_id: 'assign-002',
    student_id: 'std-005',
    student: mockStudents[4],
    status: 'pending', // ยังไม่ส่ง
    started_at: '2026-10-03T10:00:00',
    time_spent_seconds: 0,
    tab_switch_count: 0,
    total_time_away_seconds: 0,
    is_flagged_suspicious: false,
    total_score: undefined,
    max_total_score: 15,
  },
  {
    id: 'sub-012',
    assignment_id: 'assign-002',
    student_id: 'std-006',
    student: mockStudents[5],
    status: 'submitted',
    started_at: '2026-10-03T09:40:00',
    submitted_at: '2026-10-03T11:10:00',
    time_spent_seconds: 5400,
    tab_switch_count: 0,
    total_time_away_seconds: 0,
    is_flagged_suspicious: false,
    total_score: 14,
    max_total_score: 15,
  },
  // Submissions for assign-003 (Class 402: แบบฝึกหัดวิเคราะห์สาร)
  {
    id: 'sub-013',
    assignment_id: 'assign-003',
    student_id: 'std-001',
    student: mockStudents[0],
    status: 'submitted',
    started_at: '2026-10-02T13:00:00',
    submitted_at: '2026-10-02T13:45:00',
    time_spent_seconds: 2700,
    tab_switch_count: 1,
    total_time_away_seconds: 10,
    is_flagged_suspicious: false,
    total_score: 9.5,
    max_total_score: 10,
  },
  {
    id: 'sub-014',
    assignment_id: 'assign-003',
    student_id: 'std-002',
    student: mockStudents[1],
    status: 'late',
    started_at: '2026-10-02T16:00:00',
    submitted_at: '2026-10-02T17:10:00',
    time_spent_seconds: 4200,
    tab_switch_count: 3,
    total_time_away_seconds: 45,
    is_flagged_suspicious: false,
    total_score: 8,
    max_total_score: 10,
  },
  {
    id: 'sub-015',
    assignment_id: 'assign-003',
    student_id: 'std-003',
    student: mockStudents[2],
    status: 'submitted',
    started_at: '2026-10-02T13:10:00',
    submitted_at: '2026-10-02T13:50:00',
    time_spent_seconds: 2400,
    tab_switch_count: 0,
    total_time_away_seconds: 0,
    is_flagged_suspicious: false,
    total_score: undefined, // รอตรวจ
    max_total_score: 10,
  },
  {
    id: 'sub-016',
    assignment_id: 'assign-003',
    student_id: 'std-004',
    student: mockStudents[3],
    status: 'pending', // ยังไม่ส่ง
    started_at: '2026-10-02T13:00:00',
    time_spent_seconds: 0,
    tab_switch_count: 0,
    total_time_away_seconds: 0,
    is_flagged_suspicious: false,
    total_score: undefined,
    max_total_score: 10,
  },
  // Submissions for assign-004 (Class 501: วรรณคดีวิจักษ์ มัทนะพาธา)
  {
    id: 'sub-017',
    assignment_id: 'assign-004',
    student_id: 'std-001',
    student: mockStudents[0],
    status: 'submitted',
    started_at: '2026-10-02T15:00:00',
    submitted_at: '2026-10-02T16:20:00',
    time_spent_seconds: 4800,
    tab_switch_count: 0,
    total_time_away_seconds: 0,
    is_flagged_suspicious: false,
    total_score: 14,
    max_total_score: 15,
  },
  {
    id: 'sub-018',
    assignment_id: 'assign-004',
    student_id: 'std-002',
    student: mockStudents[1],
    status: 'pending', // ยังไม่ส่ง
    started_at: '2026-10-02T15:00:00',
    time_spent_seconds: 0,
    tab_switch_count: 0,
    total_time_away_seconds: 0,
    is_flagged_suspicious: false,
    total_score: undefined,
    max_total_score: 15,
  },
  {
    id: 'sub-019',
    assignment_id: 'assign-004',
    student_id: 'std-003',
    student: mockStudents[2],
    status: 'submitted',
    started_at: '2026-10-02T15:30:00',
    submitted_at: '2026-10-02T16:55:00',
    time_spent_seconds: 5100,
    tab_switch_count: 1,
    total_time_away_seconds: 12,
    is_flagged_suspicious: false,
    total_score: undefined, // รอตรวจ
    max_total_score: 15,
  },
];

export const mockSubmissionEvents: Record<string, SubmissionEvent[]> = {
  'sub-001': [
    {
      id: 'evt-101',
      submission_id: 'sub-001',
      event_type: 'tab_hidden',
      away_duration_seconds: 24,
      created_at: '2026-10-01T09:15:22',
      details: 'ผู้เรียนสลับแท็บเบราว์เซอร์ไปหน้าต่างอื่น (ตรวจพบบันทึก VisibilityState: hidden)',
    },
    {
      id: 'evt-102',
      submission_id: 'sub-001',
      event_type: 'tab_visible',
      created_at: '2026-10-01T09:15:46',
      details: 'ผู้เรียนกลับเข้าสู่หน้าต่างทำข้อสอบ',
    },
    {
      id: 'evt-103',
      submission_id: 'sub-001',
      event_type: 'window_blur',
      away_duration_seconds: 62,
      created_at: '2026-10-01T09:22:10',
      details: 'หน้าต่างเบราว์เซอร์สูญเสียโฟกัส (สงสัยเปิดโปรแกรมแชทหรือ AI ภายนอก)',
    },
    {
      id: 'evt-104',
      submission_id: 'sub-001',
      event_type: 'paste_attempt',
      created_at: '2026-10-01T09:23:15',
      details: 'ตรวจพบการ Paste ข้อความจำนวน 284 ตัวอักษรลงในช่องคำตอบข้อ 1',
    },
    {
      id: 'evt-105',
      submission_id: 'sub-001',
      event_type: 'window_focus',
      created_at: '2026-10-01T09:23:12',
      details: 'กลับมาโฟกัสหน้าต่างข้อสอบ',
    },
  ],
  'sub-003': [
    {
      id: 'evt-301',
      submission_id: 'sub-003',
      event_type: 'tab_hidden',
      away_duration_seconds: 35,
      created_at: '2026-10-01T10:15:00',
      details: 'สลับแท็บออกไปหน้าต่างอื่น',
    },
    {
      id: 'evt-302',
      submission_id: 'sub-003',
      event_type: 'tab_visible',
      created_at: '2026-10-01T10:15:35',
      details: 'กลับเข้าสู่หน้าต่างทำข้อสอบ',
    },
  ],
};

export const mockSubmissionAnswers: Record<string, Record<string, SubmissionAnswer>> = {
  // Keyed by submission_id -> question_id
  'sub-001': {
    'q-001': {
      id: 'ans-101',
      submission_id: 'sub-001',
      question_id: 'q-001',
      text_answer:
        'ข้อเท็จจริง คือ ข้อความที่แสดงเรื่องราว เหตุการณ์ หรือความจริงที่พิสูจน์ได้ตามหลักฐานประจักษ์ เช่น "พระบรมมหาราชวังตั้งอยู่ในเขตพระนคร กรุงเทพมหานคร"\n\nส่วนข้อคิดเห็น คือ ข้อความที่แสดงความรู้สึก การคาดคะเน หรือทัศนะส่วนบุคคล เช่น "การเที่ยวชมโบราณสถานในกรุงเทพมหานครช่วยสร้างความเพลิดเพลินและคุ้มค่าแก่การเรียนรู้อย่างยิ่ง"',
      ai_mock_score: 4.8,
      ai_confidence: 0.95,
      ai_feedback:
        'นักเรียนอธิบายนิยามของข้อเท็จจริงและข้อคิดเห็นได้ถูกต้องแม่นยำ พร้อมทั้งยกตัวอย่างประโยคทั้งสองประเภทที่สอดคล้องกับนิยามอย่างชัดเจน ความตรงตามเกณฑ์รูบริก 96%',
      teacher_score: 4.5, // Primary teacher score
      teacher_comment: 'อธิบายได้ดีมาก ชัดเจนและเข้าใจง่าย (หมายเหตุ: มีการวางข้อความจากภายนอก ควรตรวจสอบเพิ่มเติม)',
      graded_at: '2026-10-01T11:20:00',
      co_grades: {
        'teacher-tippanan': {
          teacher_id: 'teacher-tippanan',
          teacher_name: 'ครูธิปนรรจ์ พรายหนู (Primary Owner)',
          teacher_role: 'primary',
          score: 4.5,
          comment: 'อธิบายได้ดีมาก ชัดเจนและเข้าใจง่าย (หมายเหตุ: มีการวางข้อความจากภายนอก ควรตรวจสอบเพิ่มเติม)',
          graded_at: '2026-10-01T11:20:00',
        },
        'teacher-somchai': {
          teacher_id: 'teacher-somchai',
          teacher_name: 'ครูสมชาย วิทยากร (Co-Teacher / IRR)',
          teacher_role: 'assistant',
          score: 4.0,
          comment: 'เนื้อหาถูกต้องตามรูบริก แต่หักคะแนนส่วนการคัดลอกข้อความเล็กน้อย',
          graded_at: '2026-10-01T11:35:00',
        },
      },
    },
    'q-002': {
      id: 'ans-102',
      submission_id: 'sub-001',
      question_id: 'q-002',
      file_url: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=1000&auto=format&fit=crop&q=80',
      ai_mock_score: 4.5,
      ai_confidence: 0.90,
      ai_feedback:
        'แผนภาพความคิดสรุประดับภาษาได้ครบ 3 ระดับ มีการแตกกิ่งย่อยระบุลักษณะคำและบริบทการใช้งานถูกต้อง ลายมืออ่านง่าย เป็นระเบียบเรียบร้อย',
      teacher_score: 4.5,
      teacher_comment: 'แผนภาพสมบูรณ์ดีมาก แสดงการจำแนกระดับภาษาชัดเจน',
      graded_at: '2026-10-01T11:22:00',
      co_grades: {
        'teacher-tippanan': {
          teacher_id: 'teacher-tippanan',
          teacher_name: 'ครูธิปนรรจ์ พรายหนู (Primary Owner)',
          teacher_role: 'primary',
          score: 4.5,
          comment: 'แผนภาพสมบูรณ์ดีมาก แสดงการจำแนกระดับภาษาชัดเจน',
          graded_at: '2026-10-01T11:22:00',
        },
        'teacher-somchai': {
          teacher_id: 'teacher-somchai',
          teacher_name: 'ครูสมชาย วิทยากร (Co-Teacher / IRR)',
          teacher_role: 'assistant',
          score: 4.5,
          comment: 'การจำแนกเนื้อหาตรงเกณฑ์ความสอดคล้อง',
          graded_at: '2026-10-01T11:37:00',
        },
      },
    },
    'q-003': {
      id: 'ans-103',
      submission_id: 'sub-001',
      question_id: 'q-003',
      text_answer: 'ข. บ่ายวันนี้อากาศอบอ้าวมาก คาดว่าตอนเย็นฝนน่าจะตกหนักแน่นอน',
      ai_mock_score: 5.0,
      ai_confidence: 1.0,
      ai_feedback: 'ตรวจคำตอบปรนัยอัตโนมัติ: ตอบถูกต้องตามเฉลย (ข้อความเป็นการคาดคะเน)',
      teacher_score: 5.0,
      teacher_comment: 'คำตอบปรนัยถูกต้อง',
      graded_at: '2026-10-01T09:42:00',
      co_grades: {
        'teacher-tippanan': {
          teacher_id: 'teacher-tippanan',
          teacher_name: 'ครูธิปนรรจ์ พรายหนู (Primary Owner)',
          teacher_role: 'primary',
          score: 5.0,
          comment: 'คำตอบปรนัยถูกต้อง',
          graded_at: '2026-10-01T09:42:00',
        },
        'teacher-somchai': {
          teacher_id: 'teacher-somchai',
          teacher_name: 'ครูสมชาย วิทยากร (Co-Teacher / IRR)',
          teacher_role: 'assistant',
          score: 5.0,
          comment: 'ถูกต้องสมบูรณ์',
          graded_at: '2026-10-01T11:40:00',
        },
      },
    },
    'q-004': {
      id: 'ans-104',
      submission_id: 'sub-001',
      question_id: 'q-004',
      text_answer: 'จริง (True)',
      ai_mock_score: 5.0,
      ai_confidence: 1.0,
      ai_feedback: 'ตรวจคำตอบถูก/ผิดอัตโนมัติ: ตอบถูกต้องตามเฉลย',
      teacher_score: 5.0,
      teacher_comment: 'เข้าใจหลักการใช้ระดับภาษาในบริบททางการถูกต้อง',
      graded_at: '2026-10-01T09:42:00',
      co_grades: {
        'teacher-tippanan': {
          teacher_id: 'teacher-tippanan',
          teacher_name: 'ครูธิปนรรจ์ พรายหนู (Primary Owner)',
          teacher_role: 'primary',
          score: 5.0,
          comment: 'เข้าใจหลักการใช้ระดับภาษาในบริบททางการถูกต้อง',
          graded_at: '2026-10-01T09:42:00',
        },
      },
    },
  },
  'sub-003': {
    'q-001': {
      id: 'ans-301',
      submission_id: 'sub-003',
      question_id: 'q-001',
      text_answer: 'ข้อเท็จจริงคือเรื่องจริงที่เกิดขึ้น ส่วนข้อคิดเห็นคือคิดเอาเอง',
      ai_mock_score: 3.0,
      ai_confidence: 0.85,
      ai_feedback:
        'นักเรียนเข้าใจแนวคิดเบื้องต้น แต่ขาดการอธิบายคำจำกัดความอย่างเป็นทางการ และไม่ได้ยกตัวอย่างประโยคตามที่โจทย์กำหนด',
      teacher_score: undefined,
      teacher_comment: undefined,
    },
  },
  'sub-004': {
    'q-001': {
      id: 'ans-401',
      submission_id: 'sub-004',
      question_id: 'q-001',
      text_answer:
        'ข้อเท็จจริง หมายถึง สิ่งหรือเรื่องราวที่มีความเป็นจริง สามารถพิสูจน์ได้ มีหลักฐานอ้างอิงชัดเจน เช่น ประเทศไทยตั้งอยู่ในทวีปเอเชีย ส่วนข้อคิดเห็น คือ ความรู้สึก ความคิดเห็น หรือการคาดคะเนของบุคคล เช่น ฤดูหนาวในภาคเหนือของไทยมีความสวยงามที่สุด',
      ai_mock_score: 5.0,
      ai_confidence: 0.98,
      ai_feedback:
        'คำตอบดีเยี่ยม มีการอ้างอิงนิยามและยกตัวอย่างชัดเจน สมบูรณ์ตามเกณฑ์ประเมิน 100%',
      teacher_score: undefined,
      teacher_comment: undefined,
    },
  },
};
